version: "3.8"
services:
  app:
    build: ./caddy-security-proxy
    image: cloud.canister.io:5000/ashenblue/caddy-security-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy_public
    networks:
      - caddy_public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

networks:
  caddy_public:
    external: true

volumes:
  data: {}
