[global]
  checkNewVersion = true

# Enable the Dashboard
[api]
  # maybe get to it over http?
  insecure = true
  dashboard = true

# Write out Traefik logs
[log]
  level = "INFO"
  filePath = "/traefik.log"

[entryPoints.http]
  address = ":80"
  # Redirect to HTTPS (why wouldn't you?)
  [entryPoints.http.http.redirections.entryPoint]
    to = "https"
    scheme = "https"

[entryPoints.https]
  address = ":443"
  [entryPoints.https.http.tls]
    certResolver = "main"

# Let's Encrypt
[certificatesResolvers.le.acme]
  email = "ashen@cobaltrain.net"
  storage = "/acme/acme.json"
  # uncomment to use staging CA for testing
  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  tlschallenge = true

# Docker Traefik provider
[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  swarmMode = true
  watch = true